apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: shopnow
  labels:
    app: frontend
    app.kubernetes.io/part-of: shopnow
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080   # Access via: $(minikube ip):30080
      protocol: TCP
