{{- if .Values.admin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "shopnow.labels" . | nindent 4 }}
    app: admin
spec:
  type: NodePort
  selector:
    {{- include "shopnow.selectorLabels" (dict "component" "admin" "context" .) | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.admin.port }}
      targetPort: {{ .Values.admin.port }}
      nodePort: {{ .Values.admin.nodePort }}
      protocol: TCP
{{- end }}
