{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "shopnow.labels" . | nindent 4 }}
    app: frontend
spec:
  type: NodePort
  selector:
    {{- include "shopnow.selectorLabels" (dict "component" "frontend" "context" .) | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      nodePort: {{ .Values.frontend.nodePort }}
      protocol: TCP
{{- end }}
