{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "shopnow.labels" . | nindent 4 }}
    app: mongodb
spec:
  type: ClusterIP
  clusterIP: None   # Headless — enables mongodb-0.mongodb-service DNS for StatefulSet
  selector:
    {{- include "shopnow.selectorLabels" (dict "component" "mongodb" "context" .) | nindent 4 }}
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
      protocol: TCP
{{- end }}
