{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "shopnow.labels" . | nindent 4 }}
    app: mongodb
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.auth.rootUsername | b64enc | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
  MONGO_INITDB_DATABASE: {{ .Values.mongodb.auth.database | b64enc | quote }}
  MONGODB_URI: {{ include "shopnow.mongodbURI" . | b64enc | quote }}
{{- end }}
